In [3]:
import seaborn as sns
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import hashlib as hl

In [57]:
data = pd.read_csv("athlete_events.csv")

In [ ]:
data["Name"] = data["Name"].apply(lambda x: hl.sha256(str(x).encode("utf-8")).hexdigest())

In [ ]:
data = data[(data["Team"] == "France")&
            (data["Season"] == "Summer")&
            (data["Medal"].isin(["Bronze", "Silver", "Gold"]))]
data.head(50).sort_values(by="Event")
data

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
150,56,Ren Abadie,M,21.0,NaN,NaN,France,FRA,1956 Summer,1956,Summer,Melbourne,Cycling,"Cycling Men's Road Race, Team",Gold
173,73,Luc Abalo,M,23.0,182.0,86.0,France,FRA,2008 Summer,2008,Summer,Beijing,Handball,Handball Men's Handball,Gold
174,73,Luc Abalo,M,27.0,182.0,86.0,France,FRA,2012 Summer,2012,Summer,London,Handball,Handball Men's Handball,Gold
175,73,Luc Abalo,M,31.0,182.0,86.0,France,FRA,2016 Summer,2016,Summer,Rio de Janeiro,Handball,Handball Men's Handball,Silver
200,93,Jol Marc Abati,M,38.0,190.0,85.0,France,FRA,2008 Summer,2008,Summer,Beijing,Handball,Handball Men's Handball,Gold
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
264255,132240,"Abdelghani ""Ghani"" Yalouz",M,28.0,168.0,69.0,France,FRA,1996 Summer,1996,Summer,Atlanta,Wrestling,"Wrestling Men's Lightweight, Greco-Roman",Silver
265464,132845,Hubert Yencesse,M,48.0,NaN,NaN,France,FRA,1948 Summer,1948,Summer,London,Art Competitions,"Art Competitions Mixed Sculpturing, Statues",Bronze
265879,133031,Tony Victor James Yoka,M,24.0,200.0,105.0,France,FRA,2016 Summer,2016,Summer,Rio de Janeiro,Boxing,Boxing Men's Super-Heavyweight,Gold
266984,133577,Grce Zaadi Deuna,F,23.0,171.0,66.0,France,FRA,2016 Summer,2016,Summer,Rio de Janeiro,Handball,Handball Women's Handball,Silver
267785,133968,Jean-Louis Zanon,M,23.0,180.0,70.0,France,FRA,1984 Summer,1984,Summer,Los Angeles,Football,Football Men's Football,Gold

In [64]:
data = data[(data["Team"] == "France")&
            (data["Season"] == "Summer")]
gold = data[data["Medal"].isin(["Gold"])]
silver = data[data["Medal"].isin(["Silver"])]
bronze = data[data["Medal"].isin(["Bronze"])]
gold.drop_duplicates(subset=["Event"]).count()
silver.drop_duplicates(subset=["Event"]).count()
bronze.drop_duplicates(subset=["Event"]).count()

ID        176
Name      176
Sex       176
Age       169
Height    110
Weight    106
Team      176
NOC       176
Games     176
Year      176
Season    176
City      176
Sport     176
Event     176
Medal     176
dtype: int64

In [11]:
data[data["Medal"] == "Bronze"].sort_values(by="Event").head(40)

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
238965,119801,Jrme Cdric Thomas,M,21.0,168.0,51.0,France,FRA,2000 Summer,2000,Summer,Sydney,Boxing,Boxing Men's Flyweight,Bronze
14519,7815,Anne-Lise Bardet,F,30.0,169.0,58.0,France,FRA,2000 Summer,2000,Summer,Sydney,Canoeing,"Canoeing Women's Kayak Singles, Slalom",Bronze
142011,71236,Jeannie Longo-Ciprelli,F,41.0,164.0,48.0,France,FRA,2000 Summer,2000,Summer,Sydney,Cycling,Cycling Women's Individual Time Trial,Bronze
70322,35803,Laura lodie Flessel-Colovic,F,28.0,171.0,55.0,France,FRA,2000 Summer,2000,Summer,Sydney,Fencing,"Fencing Women's epee, Individual",Bronze
242868,121623,Stphane Andr Michel Traineau,M,33.0,192.0,98.0,France,FRA,2000 Summer,2000,Summer,Sydney,Judo,Judo Men's Half-Heavyweight,Bronze
53639,27507,Frdric Alain Demontfaucon,M,26.0,182.0,90.0,France,FRA,2000 Summer,2000,Summer,Sydney,Judo,Judo Men's Middleweight,Bronze
38545,19827,Thibaud Chapelle,M,23.0,175.0,72.0,France,FRA,2000 Summer,2000,Summer,Sydney,Rowing,Rowing Men's Lightweight Double Sculls,Bronze
242576,121493,Pascal Andr Jean Touron,M,27.0,176.0,70.0,France,FRA,2000 Summer,2000,Summer,Sydney,Rowing,Rowing Men's Lightweight Double Sculls,Bronze
52471,26960,Virginie Dedieu,F,21.0,164.0,52.0,France,FRA,2000 Summer,2000,Summer,Sydney,Synchronized Swimming,Synchronized Swimming Women's Duet,Bronze
138971,69811,Myriam Lignot,F,25.0,169.0,53.0,France,FRA,2000 Summer,2000,Summer,Sydney,Synchronized Swimming,Synchronized Swimming Women's Duet,Bronze
77809,39506,Pascal Guy Gentil,M,27.0,198.0,95.0,France,FRA,2000 Summer,2000,Summer,Sydney,Taekwondo,Taekwondo Men's Heavyweight,Bronze
54828,28098,Arnaud Laurent Di Pasquale,M,21.0,185.0,80.0,France,FRA,2000 Summer,2000,Summer,Sydney,Tennis,Tennis Men's Singles,Bronze

In [24]:
italy = pd.read_csv("athlete_events.csv")
italy = italy[(italy["Team"] == "Italy")&
              (italy["Year"] == 2000)]
italy

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
220,106,Agostino Abbagnale,M,34.0,188.0,96.0,Italy,ITA,2000 Summer,2000,Summer,Sydney,Rowing,Rowing Men's Quadruple Sculls,Gold
262,134,Christian Abbiati,M,23.0,192.0,90.0,Italy,ITA,2000 Summer,2000,Summer,Sydney,Football,Football Men's Football,NaN
264,136,Alessandro Abbio,M,29.0,195.0,85.0,Italy,ITA,2000 Summer,2000,Summer,Sydney,Basketball,Basketball Men's Basketball,NaN
2675,1490,Clelia Ailara,F,28.0,169.0,61.0,Italy,ITA,2000 Summer,2000,Summer,Sydney,Softball,Softball Women's Softball,NaN
4636,2642,Erica Alfridi,F,32.0,168.0,52.0,Italy,ITA,2000 Summer,2000,Summer,Sydney,Athletics,Athletics Women's 20 kilometres Walk,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
267570,133862,Gianluca Zambrotta,M,23.0,182.0,74.0,Italy,ITA,2000 Summer,2000,Summer,Sydney,Football,Football Men's Football,NaN
267656,133906,Marco Zanchi,M,23.0,178.0,74.0,Italy,ITA,2000 Summer,2000,Summer,Sydney,Football,Football Men's Football,NaN
267710,133932,Cristiano Zanetti,M,23.0,182.0,78.0,Italy,ITA,2000 Summer,2000,Summer,Sydney,Football,Football Men's Football,NaN
268550,134351,Matteo Zennaro,M,24.0,192.0,95.0,Italy,ITA,2000 Summer,2000,Summer,Sydney,Fencing,"Fencing Men's Foil, Individual",NaN
268551,134351,Matteo Zennaro,M,24.0,192.0,95.0,Italy,ITA,2000 Summer,2000,Summer,Sydney,Fencing,"Fencing Men's Foil, Team",Bronze