* Athletics
* Swimming
* Fencing
* Football

In [1]:
import pandas as pd
import plotly.express as px

In [3]:
df = pd.read_csv("../data/athlete_events.csv")
noc = pd.read_csv("../data/noc_regions.csv")

df.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN

In [7]:
sports = ['Athletics', 'Swimming', 'Fencing', 'Football']
sport_df = df[df['Sport'].isin(sports)]
sport_df.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
26,8,"Cornelia ""Cor"" Aalten (-Strannood)",F,18.0,168.0,NaN,Netherlands,NED,1932 Summer,1932,Summer,Los Angeles,Athletics,Athletics Women's 100 metres,NaN
27,8,"Cornelia ""Cor"" Aalten (-Strannood)",F,18.0,168.0,NaN,Netherlands,NED,1932 Summer,1932,Summer,Los Angeles,Athletics,Athletics Women's 4 x 100 metres Relay,NaN
29,10,"Einar Ferdinand ""Einari"" Aalto",M,26.0,NaN,NaN,Finland,FIN,1952 Summer,1952,Summer,Helsinki,Swimming,Swimming Men's 400 metres Freestyle,NaN
35,15,Arvo Ossian Aaltonen,M,22.0,NaN,NaN,Finland,FIN,1912 Summer,1912,Summer,Stockholm,Swimming,Swimming Men's 200 metres Breaststroke,NaN

In [8]:
medals_by_country = (
    sport_df.dropna(subset=['Medal'])
    .groupby(['Sport', 'NOC'])
    .size()
    .reset_index(name='Antal')
)

fig = px.bar(
    medals_by_country,
    x='NOC',
    y='Antal',
    color='Sport',
    title='Medaljfördelning mellan länder per sport'
)
fig.show()

In [9]:
fig = px.box(
    sport_df.dropna(subset=['Age']),
    x='Sport',
    y='Age',
    color='Sport',
    title='Åldersfördelning i olika sporter'
)
fig.show()

### Sammanfattning

Jag analyserade 4 sporter (Athletice, Swimming, Fencing, Football).
Resultaten visar att Frankrike är starkt i Fencing medan länder som USA dominerar i Athletics och Swimming.
De flesta atleter är mellan 20-30 år gamla, men i vissa sporter som Fencing finns även äldre deltagare.